// styles/tokens.css와 theme.css에 등록된 항목을 소개합니다. 토큰 변경 시 이 안내 목록도 함께 갱신해주세요.
export const colors = [
  {
    name: 'grayscale-50',
    value: '#fafafa',
    background: 'bg-grayscale-50',
    text: 'text-grayscale-50',
    border: 'border-grayscale-50',
  },
  {
    name: 'grayscale-100',
    value: '#f2f2f2',
    background: 'bg-grayscale-100',
    text: 'text-grayscale-100',
    border: 'border-grayscale-100',
  },
  {
    name: 'grayscale-200',
    value: '#dddddd',
    background: 'bg-grayscale-200',
    text: 'text-grayscale-200',
    border: 'border-grayscale-200',
  },
  {
    name: 'grayscale-300',
    value: '#cccccc',
    background: 'bg-grayscale-300',
    text: 'text-grayscale-300',
    border: 'border-grayscale-300',
  },
  {
    name: 'grayscale-400',
    value: '#a4a4a4',
    background: 'bg-grayscale-400',
    text: 'text-grayscale-400',
    border: 'border-grayscale-400',
  },
  {
    name: 'grayscale-500',
    value: '#737373',
    background: 'bg-grayscale-500',
    text: 'text-grayscale-500',
    border: 'border-grayscale-500',
  },
  {
    name: 'grayscale-600',
    value: '#535353',
    background: 'bg-grayscale-600',
    text: 'text-grayscale-600',
    border: 'border-grayscale-600',
  },
  {
    name: 'grayscale-700',
    value: '#333333',
    background: 'bg-grayscale-700',
    text: 'text-grayscale-700',
    border: 'border-grayscale-700',
  },
  {
    name: 'grayscale-800',
    value: '#262626',
    background: 'bg-grayscale-800',
    text: 'text-grayscale-800',
    border: 'border-grayscale-800',
  },
  {
    name: 'grayscale-900',
    value: '#121212',
    background: 'bg-grayscale-900',
    text: 'text-grayscale-900',
    border: 'border-grayscale-900',
  },
  {
    name: 'orange-100',
    value: '#fff8e4',
    background: 'bg-orange-100',
    text: 'text-orange-100',
    border: 'border-orange-100',
  },
  {
    name: 'orange-200',
    value: '#feefdc',
    background: 'bg-orange-200',
    text: 'text-orange-200',
    border: 'border-orange-200',
  },
  {
    name: 'orange-300',
    value: '#ffd19b',
    background: 'bg-orange-300',
    text: 'text-orange-300',
    border: 'border-orange-300',
  },
  {
    name: 'orange-400',
    value: '#ffa96c',
    background: 'bg-orange-400',
    text: 'text-orange-400',
    border: 'border-orange-400',
  },
  {
    name: 'orange-500',
    value: '#ff8442',
    background: 'bg-orange-500',
    text: 'text-orange-500',
    border: 'border-orange-500',
  },
  {
    name: 'orange-600',
    value: '#ef6c00',
    background: 'bg-orange-600',
    text: 'text-orange-600',
    border: 'border-orange-600',
  },
  {
    name: 'orange-700',
    value: '#dc5203',
    background: 'bg-orange-700',
    text: 'text-orange-700',
    border: 'border-orange-700',
  },
  {
    name: 'orange-menu-active',
    value: '#ef7c00',
    background: 'bg-orange-menu-active',
    text: 'text-orange-menu-active',
    border: 'border-orange-menu-active',
  },
  {
    name: 'orange-menu-background',
    value: '#fff3e4',
    background: 'bg-orange-menu-background',
    text: 'text-orange-menu-background',
    border: 'border-orange-menu-background',
  },
  {
    name: 'orange-alpha-20',
    value: 'rgb(255 158 89 / 20%)',
    background: 'bg-orange-alpha-20',
    text: 'text-orange-alpha-20',
    border: 'border-orange-alpha-20',
  },
  {
    name: 'orange-alpha-30',
    value: 'rgb(177 77 1 / 30%)',
    background: 'bg-orange-alpha-30',
    text: 'text-orange-alpha-30',
    border: 'border-orange-alpha-30',
  },
  {
    name: 'blue-100',
    value: '#c0e8e4',
    background: 'bg-blue-100',
    text: 'text-blue-100',
    border: 'border-blue-100',
  },
  {
    name: 'blue-200',
    value: '#00d4be',
    background: 'bg-blue-200',
    text: 'text-blue-200',
    border: 'border-blue-200',
  },
  {
    name: 'blue-300',
    value: '#009d97',
    background: 'bg-blue-300',
    text: 'text-blue-300',
    border: 'border-blue-300',
  },
] as const;
export const typography = [
  {
    className: 'text-xs',
    size: '0.75rem',
    lineHeight: '1rem',
    pixels: '12 / 16px',
  },
  {
    className: 'text-sm',
    size: '0.875rem',
    lineHeight: '1.25rem',
    pixels: '14 / 20px',
  },
  {
    className: 'text-base',
    size: '1rem',
    lineHeight: '1.5rem',
    pixels: '16 / 24px',
  },
  {
    className: 'text-lg',
    size: '1.125rem',
    lineHeight: '1.75rem',
    pixels: '18 / 28px',
  },
  {
    className: 'text-xl',
    size: '1.25rem',
    lineHeight: '1.875rem',
    pixels: '20 / 30px',
  },
  {
    className: 'text-2xl',
    size: '1.5rem',
    lineHeight: '2rem',
    pixels: '24 / 32px',
  },
  {
    className: 'text-3xl',
    size: '1.875rem',
    lineHeight: '2.25rem',
    pixels: '30 / 36px',
  },
  {
    className: 'text-display-md',
    size: '2.25rem',
    lineHeight: '2.75rem',
    pixels: '36 / 44px',
  },
  {
    className: 'text-display-lg',
    size: '3rem',
    lineHeight: '3.25rem',
    pixels: '48 / 52px',
  },
  {
    className: 'text-display-xl',
    size: '5rem',
    lineHeight: '4.625rem',
    pixels: '80 / 74px',
  },
] as const;
export const weights = [
  { className: 'font-normal', value: 400 },
  { className: 'font-medium', value: 500 },
  { className: 'font-semibold', value: 600 },
  { className: 'font-bold', value: 700 },
] as const;

// 라이트·다크를 동시에 보여주기 위한 미리보기 전용 값입니다. 전역 테마는 변경하지 않습니다.
export const themeTokens = [
  {
    className: 'bg-background',
    variable: '--background',
    light: '#f0f0f0',
    dark: '#0a0a0a',
    usage: '페이지 전체 배경',
  },
  {
    className: 'bg-white-section',
    variable: '--white-section',
    light: '#ffffff',
    dark: '#121212',
    usage: '라이트에서 흰색인 사이드바·카드·팝업',
  },
  {
    className: 'text-heading',
    variable: '--heading',
    light: '#000000',
    dark: '#ffffff',
    usage: '제목',
  },
  {
    className: 'text-foreground',
    variable: '--foreground',
    light: '#333333',
    dark: '#f2f2f2',
    usage: '기본 본문',
  },
  {
    className: 'text-muted',
    variable: '--text-muted',
    light: '#737373',
    dark: '#bbbbbb',
    usage: '보조 텍스트',
  },
  {
    className: 'text-subtle',
    variable: '--text-subtle',
    light: '#a0a0a0',
    dark: '#a4a4a4',
    usage: '약한 안내 텍스트',
  },
  {
    className: 'border-subtle',
    variable: '--border-subtle',
    light: '#dddddd',
    dark: '#535353',
    usage: '내 정보 링크 등 연한 일반 테두리 (두께는 border로 별도 지정)',
  },
  {
    className: 'border-default',
    variable: '--border-default',
    light: '#333333',
    dark: '#535353',
    usage: '인풋 테두리 색상 (두께는 border로 별도 지정)',
  },
] as const;

export const shadows = [
  { className: 'shadow-md', value: '0 0 1.875rem 0 #0000000D', blur: '30px' },
  { className: 'shadow-lg', value: '0 0 3.75rem 0 #0000000D', blur: '60px' },
] as const;
